### ISSUE TITLE
Exclude filetype please?

### ISSUE THREAD

**Issue by nyngwang** [gorbit99/codewindow.nvim#3]
Unfortunately, I have a file-tree plugin at RHS.

<img src="https://user-images.githubusercontent.com/24765272/196318628-54885dae-3ef9-4d72-abed-74b3da35f006.png" width="300">

**Comment by gorbit99** [comment]
Just pushed a commit trying to add something like that in.
It's done by putting in 
```lua
exclude_filetypes = {...}
```
into your setup config. Give it a try

**Comment by nyngwang** [comment]
@gorbit99 Just confirmed it works :) Thanks for the quick fix. Can be safely closed I think!

**Comment by gorbit99** [comment]
Fixed by https://github.com/gorbit99/codewindow.nvim/commit/b04c584e631367ca8ff67924c2ba3f06de2bb9f5

**Comment by ASoldo** [comment]
I have run nvim +PackerSync and it fixed minimap overlapping with status bar but after i add 
```lua
codewindow.setup({
        z_index = 1,
        minimap_width = 10,
        exclude_filetypes = {}
})
```
but minimap is still showing in my neotree buffer.

**Comment by nyngwang** [comment]
@ASoldo You will need to use `exclude_filetypes = { 'neo-tree' }`, not `{}`.

**Comment by ASoldo** [comment]
For any future reference: if we have lsp symbol outline buffer that is part of the 'neovim/nvim-lspconfig' we allways need to put whole package name in exclude_filetypes? -im using Astro Nvim so there are some extra buffers that I need to exclude.

**Comment by gorbit99** [comment]
@ASoldo whenever you have a problem with a specific buffer, go into it with your cursor, type ":set filetype?" and whatever it gives back as the filetype is whatever should go into the exclude option.
If the buffer doesn't have a filetype yet, I'm afraid the cleanest solution is telling the plugin maintainers about it
